### ISSUE TITLE
Supports Arabic characters

### ISSUE THREAD

**Issue by AymanGX** [NyashniyVladya/Translator3000#7]
Hello. It seems that your tool does not support Arabic. When I start the game, the text appears in the form of squares. Can you solve this problem please.

**Comment by NyashniyVladya** [comment]
Greetings. The problem is not my tool. If you see squares instead of characters, it means that the font in the game does not support characters from your language (Arabic in this case).
For such cases I added a parameter **_font_** in the settings file. Find a font that supports Arabic characters, put it in the **_game_** folder and write its name in the settings file.
This is also written in the instructions [on the release page](https://github.com/NyashniyVladya/Translator3000/releases) (paragraph 4.8.1).

**Comment by NyashniyVladya** [comment]
Actually, I could solve this problem by adding to the **_.rpa_** file fonts for all languages supported by Google...
But, on the other hand, this would greatly increase the final size of the archive, which is not good...

In any case, I understand that the programmer must implement the logic of the project to minimize the user's work on setting up the tool as much as possible. And the fact that the user has to search for a font by himself, type in his name and everything else is certainly not the answer and something has to be done about it.

I don't know yet... I'll think about the best way to solve this issue.

**Comment by AymanGX** [comment]
Thank you for all the information, sure this is a great help.
